### PR TITLE
Portuguese translation (european pt_PT)

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Added portuguese (pt_PT) language files up to last .pot file (2yrs old).
Some strings added manually because .pot file is not up to date to the
strings on relase/developer branches.

### CODE REVIEW

**Comment by pedro-mendonca** [comment]
Hi
I've sweeped source code with poedit and updated .pot file. No more manually added strings :)
Found some new strings and updated portuguese language files also.

**Comment by archetyped** [comment]
Thanks, I'll review this and add it in the next update.

**Comment by pedro-mendonca** [comment]
@archetyped just added last updated strings

**Comment by archetyped** [comment]
Thank you.  I'll add it in an upcoming update.

**Pull request closed without merging**
